export const btns = [
  "All",
  "Smartphones",
  "Gadget Reviews",
  "Podcasts",
  "Interviews",
  "Music Videos",
  "Roasting",
  "Standup Comedy",
  "Tech News",
  "Vlogging",
  "Finance Tips",
  "Business Case Studies",
  "Hindi Music",
  "Web Series",
  "Fitness & Health",
  "Mixes",
  "Startups",
  "Tech",
  "Coding",
  "React",
  "AI",
  "Cricket",
  "Finance",
  "Movies",
  "Gaming",
  "Live",
  "Web Dev",
  "Motivation",
  "Travel Vlogs",
  "Food Reviews",
  "DIY Projects",
  "Science Explained",
  "History Documentaries",
  "Photography",
  "Art & Design",
  "Education",
  "Book Summaries",
  "Spirituality",
  "Self-Improvement",
  "Fashion",
  "Beauty Tips",
  "Parenting",  
  "Environment",
  "Space Exploration",
  "Automobiles",
  "Sports Analysis",
  "News Commentary",
  "Language Learning",
  "Cooking Tutorials"
];

export const videos = [
  {
    id: "1",
    title: "Dhurandhar - Title Track | Ranveer Singh, Shashwat Sachdev, Hanumankind, Jasmine Sandlas, Aditya Dhar",
    channel: {
      name: "Saregama Music",
      id: "SaregamaMusic",
      profileUrl: "https://ui-avatars.com/api/?name=Saregama+Music&background=eab308&color=fff&size=48",
      verified: true,
    },
    views: 148000000,
    postedAt: new Date("2025-10-16"),
    duration: 159,
    thumbnailUrl: "https://i.ytimg.com/vi/1a5nyrMtRsk/maxresdefault.jpg",
  },
  {
    id: "2",
    title: "Khan Sir on World War 3, India vs Pakistan, China, Trump & Epstein Files | FO485 Raj Shamani",
    channel: {
      name: "Raj Shamani",
      id: "rajshamani",
      profileUrl: "https://ui-avatars.com/api/?name=Raj+Shamani&background=2563eb&color=fff&size=48",
      verified: true,
    },
    views: 13000000,
    postedAt: new Date("2026-03-19"),
    duration: 5900,
    thumbnailUrl: "https://i.ytimg.com/vi/VAtgcFtqIqw/maxresdefault.jpg", 
  },
  {
    id: "3",
    title: "Dulquer Buys the ENTIRE Shop After Being INSULTED! 😱🔥 | Lucky Baskhar | Hindi Clip | Netflix India",
    channel: {
      name: "Netflix India",
      id: "NetflixIndiaOfficial",
      profileUrl: "https://ui-avatars.com/api/?name=Netflix+India&background=E50914&color=fff&size=48](https://ui-avatars.com/api/?name=Netflix+India&background=E50914&color=fff&size=48",
      verified: true,
    },
    views: 8200000,
    postedAt: new Date("2025-03-17"),
    duration: 293,
    thumbnailUrl: "https://i.ytimg.com/vi/jcM7YBMvkbE/maxresdefault.jpg", 
  },
  {
    id: "4",
    title: "Samsung Galaxy S26 Ultra Is Here! Privacy Display Magic!🔥🔥🔥",
    channel: {
      name: "Technical Guruji",
      id: "TechnicalGuruji",
      profileUrl: "https://ui-avatars.com/api/?name=Technical+Guruji&background=ea580c&color=fff&size=48",
      verified: true,
    },
    views: 395000,
    postedAt: new Date("2026-02-08"),
    duration: 579,
    thumbnailUrl: "https://i.ytimg.com/vi/n_b7KYMZ-Nc/maxresdefault.jpg",
  },
  {
    id: "5",
    title: "Samay Raina - STILL ALIVE (Full Special)",
    channel: {
      name: "Samay Raina",
      id: "SamayRainaOfficial",
      profileUrl: "https://ui-avatars.com/api/?name=Samay+Raina&background=10b981&color=fff&size=48",
      verified: true,
    },
    views: 58000000,
    postedAt: new Date("2026-04-5"),
    duration: 4860,
    thumbnailUrl: "https://i.ytimg.com/vi/LhpZJwUboeI/maxresdefault.jpg", 
  },
  {
    id: "6",
    title: "This Guest Combo Broke the Rules! Orry, Malaika Arora, Ravi Kishan | Kapil Sharma |Bacha Hua Content",
    channel: {
      name: "Kapil Sharma",
      id: "KapilSharmaK9",
      profileUrl: "https://ui-avatars.com/api/?name=Kapil+Sharma&background=dc2626&color=fff&size=48",
      verified: true,
    },
    views: 2000000,
    postedAt: new Date("2026-04-01"),
    duration: 560,
    thumbnailUrl: "https://i.ytimg.com/vi/6FdzQWN6qxU/maxresdefault.jpg",  
  },
  {
    id: "7",
    title: "21-Year-Old TRAPPED in ₹1 LAKH Monthly EMI! | Money Matters Ep. 108 | Ankur Warikoo Hindi",
    channel: {
      name: "Ankur Warikoo",
      id: "warikoo",
      profileUrl: "https://ui-avatars.com/api/?name=Ankur+Warikoo&background=0f766e&color=fff&size=48",
      verified: true,
    },
    views: 467000,
    postedAt: new Date("2026-04-20"),
    duration: 1179,
    thumbnailUrl: "https://i.ytimg.com/vi/JBWgPt3lrVk/maxresdefault.jpg",   
  },
  {
    id: "8",
    title: "Found Shiva In Varanasi 🔱 🙏🏻",
    channel: {
      name: "BeerBiceps",
      id: "beerbiceps",
      profileUrl: "https://ui-avatars.com/api/?name=Beer+Biceps&background=16a34a&color=fff&size=48",
      verified: true,
    },
    views: 594000,
    postedAt: new Date("2026-1-01"),
    duration: 1588,
    thumbnailUrl: "https://i.ytimg.com/vi/z6kta72-RpQ/maxresdefault.jpg", 
  },
  {
    id: "9",
    title: "Jimmy Se PANGA Matlab DANGA 🔥 | Ambrish Verma | Sapne vs Everyone Season 2",
    channel: {
      name: "Prime Video India",
      id: "PrimeVideoIN",
      profileUrl: "https://ui-avatars.com/api/?name=Prime+Video&background=0ea5e9&color=fff&size=48",
      verified: true,
    },
    views: 480000,
    postedAt: new Date("2026-05-03"),
    duration: 317,
    thumbnailUrl: "https://i.ytimg.com/vi/j_DjlZJLNFE/maxresdefault.jpg",   
  },
  {
    id: "10",
    title: "Glory | Official Trailer | Divyenndu, Pulkit Samrat, Suvinder Vicky | Netflix India",
    channel: {
      name: "Netflix India",
      id: "NetflixIndiaOfficial",
      profileUrl: "https://ui-avatars.com/api/?name=Netflix&background=e11d48&color=fff&size=48",
      verified: true,
    },
    views: 23000000,
    postedAt: new Date("2026-04-20"),
    duration: 160,
    thumbnailUrl: "https://i.ytimg.com/vi/S4UI11MeljA/maxresdefault.jpg", 
  },
  {
    id: "11",
    title: "World's Strongest Man Vs Robot",
    channel: {
      name: "MrBeast",
      id: "MrBeast",
      profileUrl: "https://ui-avatars.com/api/?name=Mr+Beast&background=60a5fa&color=fff&size=48",
      verified: true,
    },
    views: 123000000,
    postedAt: new Date("2025-12-01"),
    duration: 1103,
    thumbnailUrl: "https://i.ytimg.com/vi/Ah_uuTwGOYU/maxresdefault.jpg", 
  },
  {
    id: "12",
    title: "FULL VIDEO - Anant Ambani & Radhika Merchant Wedding Full Video",
    channel: {
      name: "Daily Trending News",
      id: "DailyTrendingNews",
      profileUrl: "https://ui-avatars.com/api/?name=Daily+Trending+News&background=27272a&color=fff&size=48",
      verified: true,
    },
    views: 5200000,
    postedAt: new Date("2025-05-01"),
    duration: 3175,
    thumbnailUrl: "https://i.ytimg.com/vi/PKo6hD_tJXc/maxresdefault.jpg", 
  }
];